# Generated by Django 5.2.11 on 2026-04-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_person_birth_date_person_country_person_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
