# Generated by Django 5.2.11 on 2026-04-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_moviecredit_role_name_person_tmdb_person_id_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecredit',
            name='credit_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
