# Generated by Django 5.2.11 on 2026-04-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_moviecredit_credit_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_vote_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb_vote_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
